# Generated by Django 4.0.4 on 2022-05-22 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
    ]
