# Generated by Django 4.0.1 on 2022-03-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='admitted_at',
        ),
    ]
