# Generated by Django 4.0.1 on 2022-04-06 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Toffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toffee_name', models.CharField(max_length=35)),
                ('kid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm_app.kid')),
            ],
        ),
    ]
