# Generated by Django 4.0.1 on 2022-04-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_language_alter_toffee_kid_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=35)),
                ('shirt', models.ManyToManyField(to='orm_app.Shirt')),
            ],
        ),
    ]
