# Generated by Django 4.0.1 on 2022-03-13 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 13, 13, 27, 14, 900139))),
            ],
        ),
    ]
